spring:
  datasource:
    url: jdbc:h2:mem:kcb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: silas
    password: 8032

  logging:
    level:
      root=DEBUG:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        id:
          new_generator_mappings: false


server:
   port: 8080

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 30000000000000



UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
  all-users: Returns all registered users
  all-roles: Returns all roles in the system


AccountsController:
  balance: Returns the current account balance
  create: Creates a new bank account for the currently logged in user
  deposit: Deposits a specified amount into an account
  withdraw: Withdraws a specified amount from a specified account
  transfer: Transfers a specified amount from one specified account to another


org:
  hibernate:
    ConnectionReleaseMode: ON_CLOSE